"""Archive legacy database fields

Revision ID: 520dd626c0c9
Revises: 602a5fcc4295
Create Date: 2026-10-08 08:39:27.794453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520dd626c0c9'
down_revision: Union[str, Sequence[str], None] = '602a5fcc4295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_migration_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archive_key', sa.String(), nullable=False),
    sa.Column('source_table', sa.String(), nullable=False),
    sa.Column('source_primary_key', sa.String(), nullable=False),
    sa.Column('legacy_columns', sa.JSON(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_migration_archive_archive_key'), 'database_migration_archive', ['archive_key'], unique=True)
    op.create_index(op.f('ix_database_migration_archive_id'), 'database_migration_archive', ['id'], unique=False)
    op.create_index(op.f('ix_database_migration_archive_source_table'), 'database_migration_archive', ['source_table'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Preserve archived source data; restore a backup instead of downgrading."""
    raise RuntimeError(
        "This migration contains preserved source data and cannot be downgraded safely. "
        "Restore a verified database backup instead."
    )
