"""Initial application schema

Revision ID: 602a5fcc4295
Revises: 
Create Date: 2026-10-08 08:33:52.011775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602a5fcc4295'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absen_manual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('bulan', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama', 'tahun', 'bulan', name='uq_absen_manual_nama_periode')
    )
    op.create_index(op.f('ix_absen_manual_id'), 'absen_manual', ['id'], unique=False)
    op.create_index(op.f('ix_absen_manual_nama'), 'absen_manual', ['nama'], unique=False)
    op.create_table('attendance_upload_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_upload_batches_file_hash'), 'attendance_upload_batches', ['file_hash'], unique=False)
    op.create_index(op.f('ix_attendance_upload_batches_id'), 'attendance_upload_batches', ['id'], unique=False)
    op.create_table('business_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profil_default', sa.String(), nullable=True),
    sa.Column('jam_masuk_standar', sa.String(), nullable=True),
    sa.Column('jam_keluar_standar', sa.String(), nullable=True),
    sa.Column('dedup_threshold_menit', sa.Integer(), nullable=True),
    sa.Column('min_hari_kerja_per_minggu', sa.Integer(), nullable=True),
    sa.Column('min_minggu_berturut_alpa', sa.Integer(), nullable=True),
    sa.Column('uang_makan_default', sa.Integer(), nullable=True),
    sa.Column('potongan_telat_sedikit', sa.Integer(), nullable=True),
    sa.Column('potongan_telat_banyak_persen', sa.Float(), nullable=True),
    sa.Column('batas_telat_ringan', sa.String(), nullable=True),
    sa.Column('batas_telat_berat', sa.String(), nullable=True),
    sa.Column('potongan_pulang_duluan_sedikit', sa.Integer(), nullable=True),
    sa.Column('potongan_pulang_duluan_banyak_persen', sa.Float(), nullable=True),
    sa.Column('batas_pulang_duluan_ringan', sa.String(), nullable=True),
    sa.Column('batas_pulang_duluan_berat', sa.String(), nullable=True),
    sa.Column('bonus_lembur_per_jam', sa.Integer(), nullable=True),
    sa.Column('menit_pembulatan_lembur', sa.Integer(), nullable=True),
    sa.Column('toleransi_telat_hari_ke', sa.Integer(), nullable=True),
    sa.Column('toleransi_telat_max_menit', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_rule_id'), 'business_rule', ['id'], unique=False)
    op.create_table('employee_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('bonus_lain', sa.Float(), nullable=True),
    sa.Column('potongan_lain', sa.Float(), nullable=True),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_adjustments_id'), 'employee_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_employee_adjustments_nama'), 'employee_adjustments', ['nama'], unique=True)
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('keterangan', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tanggal')
    )
    op.create_index(op.f('ix_holidays_id'), 'holidays', ['id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_key', sa.String(), nullable=True),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('telegram_user_id', sa.String(), nullable=True),
    sa.Column('whatsapp_user_id', sa.String(), nullable=True),
    sa.Column('kategori', sa.String(), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('tanggal_selesai', sa.Date(), nullable=False),
    sa.Column('jumlah_hari', sa.Float(), nullable=True),
    sa.Column('unpaid_leave_days', sa.Float(), nullable=False),
    sa.Column('jam_izin', sa.String(), nullable=True),
    sa.Column('alasan', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('catatan_hr', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('tipe_absensi', sa.String(), nullable=True),
    sa.Column('location_cabang', sa.String(), nullable=True),
    sa.Column('foto_bukti', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.create_index(op.f('ix_leave_requests_import_key'), 'leave_requests', ['import_key'], unique=True)
    op.create_index(op.f('ix_leave_requests_nama'), 'leave_requests', ['nama'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('cabang', sa.JSON(), nullable=True),
    sa.Column('hari_kerja', sa.JSON(), nullable=True),
    sa.Column('jam_masuk', sa.JSON(), nullable=True),
    sa.Column('jam_keluar', sa.JSON(), nullable=True),
    sa.Column('patokan_lembur', sa.JSON(), nullable=True),
    sa.Column('ikut_telat', sa.Boolean(), nullable=True),
    sa.Column('ikut_lembur', sa.Boolean(), nullable=True),
    sa.Column('ikut_kuota_hari_kerja', sa.Boolean(), nullable=True),
    sa.Column('hari_kandidat_kuota', sa.JSON(), nullable=True),
    sa.Column('min_hari_kerja', sa.Integer(), nullable=True),
    sa.Column('ikut_bonus_tanggal_merah', sa.Boolean(), nullable=True),
    sa.Column('lembur_khusus', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_code'), 'profiles', ['code'], unique=True)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('hr_master', 'hr_staff', name='roleenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('whatsapp_processed_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_processed_messages_id'), 'whatsapp_processed_messages', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_processed_messages_message_id'), 'whatsapp_processed_messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_whatsapp_processed_messages_processed_at'), 'whatsapp_processed_messages', ['processed_at'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('employee_code', sa.String(), nullable=True),
    sa.Column('nik', sa.String(), nullable=True),
    sa.Column('id_mesin', sa.String(), nullable=True),
    sa.Column('profile_code', sa.String(), nullable=False),
    sa.Column('cabang', sa.String(), nullable=True),
    sa.Column('jabatan', sa.String(), nullable=True),
    sa.Column('payroll_status', sa.String(), nullable=True),
    sa.Column('uang_makan_override', sa.Integer(), nullable=True),
    sa.Column('bpjs_kesehatan', sa.Integer(), nullable=True),
    sa.Column('bpjs_tk', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('profile_needs_review', sa.Boolean(), nullable=False),
    sa.Column('employment_status', sa.String(), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('has_custom_rules', sa.Boolean(), nullable=False),
    sa.Column('jam_masuk_override', sa.String(), nullable=True),
    sa.Column('jam_keluar_override', sa.String(), nullable=True),
    sa.Column('toleransi_telat_menit_override', sa.Integer(), nullable=True),
    sa.Column('bonus_lembur_per_jam_override', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_code'], ['profiles.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_nama'), 'employees', ['nama'], unique=False)
    op.create_index(op.f('ix_employees_nik'), 'employees', ['nik'], unique=True)
    op.create_table('attendance_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cabang', sa.String(), nullable=True),
    sa.Column('profile', sa.String(), nullable=True),
    sa.Column('jam_masuk', sa.String(), nullable=True),
    sa.Column('jam_keluar', sa.String(), nullable=True),
    sa.Column('kategori_hari', sa.String(), nullable=True),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('upload_batch_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_batch_id'], ['attendance_upload_batches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'attendance_date', name='uq_attendance_daily_employee_date')
    )
    op.create_index(op.f('ix_attendance_daily_attendance_date'), 'attendance_daily', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_daily_employee_id'), 'attendance_daily', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_daily_id'), 'attendance_daily', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_daily_upload_batch_id'), 'attendance_daily', ['upload_batch_id'], unique=False)
    op.create_table('attendance_recap_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(), nullable=False),
    sa.Column('source_file_hash', sa.String(), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('employee_code', sa.String(), nullable=True),
    sa.Column('source_nik', sa.String(), nullable=True),
    sa.Column('source_cabang', sa.String(), nullable=True),
    sa.Column('source_nama', sa.String(), nullable=True),
    sa.Column('source_payroll_status', sa.String(), nullable=True),
    sa.Column('source_payload', sa.JSON(), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=True),
    sa.Column('mark', sa.String(), nullable=True),
    sa.Column('canonical_nama', sa.String(), nullable=True),
    sa.Column('canonical_cabang', sa.String(), nullable=True),
    sa.Column('reconciliation_status', sa.String(), nullable=False),
    sa.Column('identity_warning', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_recap_records_attendance_date'), 'attendance_recap_records', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_recap_records_employee_code'), 'attendance_recap_records', ['employee_code'], unique=False)
    op.create_index(op.f('ix_attendance_recap_records_employee_id'), 'attendance_recap_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_recap_records_id'), 'attendance_recap_records', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_recap_records_source_file_hash'), 'attendance_recap_records', ['source_file_hash'], unique=False)
    op.create_index(op.f('ix_attendance_recap_records_source_key'), 'attendance_recap_records', ['source_key'], unique=True)
    op.create_table('attendance_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('leave_request_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('upload_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_request_id'], ['leave_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_batch_id'], ['attendance_upload_batches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'attendance_date', name='uq_attendance_review_employee_date')
    )
    op.create_index(op.f('ix_attendance_reviews_attendance_date'), 'attendance_reviews', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_reviews_employee_id'), 'attendance_reviews', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_reviews_id'), 'attendance_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_reviews_upload_batch_id'), 'attendance_reviews', ['upload_batch_id'], unique=False)
    op.create_table('employee_import_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('nik', sa.String(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('uang_makan_override', sa.Integer(), nullable=True),
    sa.Column('jabatan', sa.String(), nullable=True),
    sa.Column('cabang', sa.String(), nullable=False),
    sa.Column('payroll_status', sa.String(), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approved_employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_import_candidates_employee_code'), 'employee_import_candidates', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employee_import_candidates_id'), 'employee_import_candidates', ['id'], unique=False)
    op.create_table('employment_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('keterangan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employment_contracts_employee_id'), 'employment_contracts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employment_contracts_id'), 'employment_contracts', ['id'], unique=False)
    op.create_table('leave_balance_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('leave_request_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_request_id'], ['leave_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_balance_ledger_employee_id'), 'leave_balance_ledger', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_balance_ledger_id'), 'leave_balance_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_leave_balance_ledger_year'), 'leave_balance_ledger', ['year'], unique=False)
    op.create_table('whatsapp_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_audit_logs_created_at'), 'whatsapp_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_audit_logs_employee_id'), 'whatsapp_audit_logs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_audit_logs_event_type'), 'whatsapp_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_whatsapp_audit_logs_id'), 'whatsapp_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_audit_logs_phone_number'), 'whatsapp_audit_logs', ['phone_number'], unique=False)
    op.create_table('whatsapp_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_identities_employee_id'), 'whatsapp_identities', ['employee_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_identities_id'), 'whatsapp_identities', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_identities_phone_number'), 'whatsapp_identities', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Do not drop the application schema; restore a verified backup instead."""
    raise RuntimeError(
        "The initial schema migration is destructive to application data and cannot be "
        "downgraded safely. Restore a verified database backup instead."
    )
